### ISSUE TITLE
README link broken

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/iotp-adaptor#3]
Points to https://github.com/OSLC/iotp-adaptor/blob/master/iotp_adaptor/userGuide/user-guide

**Comment by berezovskyi** [comment]
https://github.com/OSLC/iotp-adaptor/blob/master/iotp_adaptor/developer-guide is broken too

**Comment by twocs** [comment]
Maybe the links on https://github.com/OSLC/iotp-adaptor/wiki should be:

https://github.com/OSLC/iotp-adaptor/wiki/User-Guide ->
https://oslc.github.io/developing-oslc-applications/iotp_adaptor/userGuide/user-guide

https://github.com/OSLC/iotp-adaptor/wiki/Developer-Guide ->
https://oslc.github.io/developing-oslc-applications/iotp_adaptor/developer-guide

Seems that only the repo owner can edit a Github wiki except through some extra steps (e.g. https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github).

**Comment by jamsden** [comment]
Done, thank you.
